# About

# Section 1 : Install and import Libraries

In [3]:
import pandas as pd
import yfinance as yf
import requests
from bs4 import BeautifulSoup
import matplotlib.pyplot as plt

# Section 2: Extracting Stock Market Data

Extract the data from yahoo finance API

In [ ]:
tesla = yf.Ticker('TSLA')
share_tesla = tesla.history(period='max').reset_index()
share_tesla

,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits
0,2010-06-29 00:00:00-04:00,1.266667,1.666667,1.169333,1.592667,281494500,0.0,0.0
1,2010-06-30 00:00:00-04:00,1.719333,2.028000,1.553333,1.588667,257806500,0.0,0.0
2,2010-07-01 00:00:00-04:00,1.666667,1.728000,1.351333,1.464000,123282000,0.0,0.0
3,2010-07-02 00:00:00-04:00,1.533333,1.540000,1.247333,1.280000,77097000,0.0,0.0
4,2010-07-06 00:00:00-04:00,1.333333,1.333333,1.055333,1.074000,103003500,0.0,0.0
...,...,...,...,...,...,...,...,...
3973,2026-04-16 00:00:00-04:00,393.809998,394.059998,381.799988,388.899994,63515100,0.0,0.0
3974,2026-04-17 00:00:00-04:00,395.920013,409.279999,391.649994,400.619995,90640000,0.0,0.0
3975,2026-04-20 00:00:00-04:00,402.579987,406.799988,388.329987,392.500000,64603900,0.0,0.0
3976,2026-04-21 00:00:00-04:00,393.000000,393.950012,385.220001,386.420013,50530600,0.0,0.0
3977,2026-04-22 00:00:00-04:00,387.559998,393.000000,385.299988,387.510010,53758836,0.0,0.0

In [25]:
gamestop = yf.Ticker('GME')
share_gamestop = gamestop.history(period='max').reset_index()
share_gamestop

,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits
0,2002-02-13 00:00:00-05:00,1.620129,1.693350,1.603296,1.691667,76216000,0.0,0.0
1,2002-02-14 00:00:00-05:00,1.712707,1.716073,1.670626,1.683250,11021600,0.0,0.0
2,2002-02-15 00:00:00-05:00,1.683250,1.687458,1.658002,1.674834,8389600,0.0,0.0
3,2002-02-19 00:00:00-05:00,1.666418,1.666418,1.578047,1.607504,7410400,0.0,0.0
4,2002-02-20 00:00:00-05:00,1.615921,1.662210,1.603296,1.662210,6892800,0.0,0.0
...,...,...,...,...,...,...,...,...
6081,2026-04-16 00:00:00-04:00,24.910000,25.490000,24.540001,25.180000,10701100,0.0,0.0
6082,2026-04-17 00:00:00-04:00,25.190001,25.340000,24.370001,24.549999,8161000,0.0,0.0
6083,2026-04-20 00:00:00-04:00,24.170000,25.049999,24.080000,24.920000,6199700,0.0,0.0
6084,2026-04-21 00:00:00-04:00,25.049999,25.330000,24.430000,24.459999,6472800,0.0,0.0
6085,2026-04-22 00:00:00-04:00,24.709999,25.735001,24.700001,25.660000,8392080,0.0,0.0

# Section 3: Additional Income/Profit Data

# Section 4: Cleaning Data

# Section 5: Visualization

# Section 6: Conclusions