# About

# Section 1 : Install and import Libraries

In [1]:
import pandas as pd
import yfinance as yf
import requests
from bs4 import BeautifulSoup
import matplotlib.pyplot as plt

In [4]:
import warnings
# Ignore all warnings
warnings.filterwarnings("ignore", category=FutureWarning)

# Section 2: Extracting Stock Market Data

Extract the data from yahoo finance API

In [2]:
tesla = yf.Ticker('TSLA')
share_tesla = tesla.history(period='max').reset_index()
share_tesla

,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits
0,2010-06-29 00:00:00-04:00,1.266667,1.666667,1.169333,1.592667,281494500,0.0,0.0
1,2010-06-30 00:00:00-04:00,1.719333,2.028000,1.553333,1.588667,257806500,0.0,0.0
2,2010-07-01 00:00:00-04:00,1.666667,1.728000,1.351333,1.464000,123282000,0.0,0.0
3,2010-07-02 00:00:00-04:00,1.533333,1.540000,1.247333,1.280000,77097000,0.0,0.0
4,2010-07-06 00:00:00-04:00,1.333333,1.333333,1.055333,1.074000,103003500,0.0,0.0
...,...,...,...,...,...,...,...,...
3985,2026-05-04 00:00:00-04:00,390.230011,394.640015,384.799988,392.510010,48765100,0.0,0.0
3986,2026-05-05 00:00:00-04:00,395.190002,402.119995,389.000000,389.369995,47780600,0.0,0.0
3987,2026-05-06 00:00:00-04:00,386.250000,401.679993,384.019989,398.730011,53465400,0.0,0.0
3988,2026-05-07 00:00:00-04:00,407.480011,415.829987,402.119995,411.790009,64294200,0.0,0.0
3989,2026-05-08 00:00:00-04:00,416.480011,431.200012,416.390015,428.350006,64880800,0.0,0.0

In [3]:
gamestop = yf.Ticker('GME')
share_gamestop = gamestop.history(period='max').reset_index()
share_gamestop

,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits
0,2002-02-13 00:00:00-05:00,1.620128,1.693350,1.603296,1.691666,76216000,0.0,0.0
1,2002-02-14 00:00:00-05:00,1.712707,1.716074,1.670626,1.683251,11021600,0.0,0.0
2,2002-02-15 00:00:00-05:00,1.683250,1.687458,1.658002,1.674834,8389600,0.0,0.0
3,2002-02-19 00:00:00-05:00,1.666418,1.666418,1.578047,1.607504,7410400,0.0,0.0
4,2002-02-20 00:00:00-05:00,1.615920,1.662210,1.603296,1.662210,6892800,0.0,0.0
...,...,...,...,...,...,...,...,...
6093,2026-05-04 00:00:00-04:00,25.110001,26.150000,23.670000,23.840000,40178600,0.0,0.0
6094,2026-05-05 00:00:00-04:00,23.209999,24.730000,22.850000,24.230000,17979600,0.0,0.0
6095,2026-05-06 00:00:00-04:00,24.299999,25.440001,23.959999,25.170000,11606500,0.0,0.0
6096,2026-05-07 00:00:00-04:00,25.120001,25.250000,23.790001,23.969999,8794000,0.0,0.0
6097,2026-05-08 00:00:00-04:00,24.139999,24.420000,23.820000,24.280001,5936000,0.0,0.0

# Section 3: Additional Income/Profit Data

### Revenue Data Extraction

For this project, the historical revenue data was extracted from Macrotrends.  
This website provides financial tables with company fundamentals, including revenue data for Tesla and GameStop.  

The purpose of using this source is to compare each company’s stock price performance with its reported revenue over time.

#### Tesla Revenue

In [19]:
url_tesla = "https://www.macrotrends.net/stocks/charts/TSLA/tesla/revenue?"
data_tsla = requests.get(url_tesla).text

In [32]:
#Parsing the data using Beautiful soup library
soup_tsla = BeautifulSoup(data_tsla, 'html.parser')

### Note on Revenue Data Source

Macrotrends was initially considered as a source for historical revenue data. However, direct requests to the website returned a Cloudflare protection page instead of the actual financial table, which prevented automated extraction.

To continue the analysis and web scraping practice, an alternative public source with accessible revenue history tables was used.

In [18]:
url_tesla = "https://companiesmarketcap.com/tesla/revenue/"
html_tesla = requests.get(url_tesla).text
html_tesla

'<!DOCTYPE html>\n<html lang="en-US">\n<head>\n<title>Tesla (TSLA) - Revenue</title>\n<meta charset="utf-8"/>\n<link rel="shortcut icon" href="https://companiesmarketcap.com/favicon.ico" type="image/x-icon">\n<link rel="apple-touch-icon" sizes="57x57" href="/img/icons/apple-icon-57x57.png">\n<link rel="apple-touch-icon" sizes="60x60" href="/img/icons/apple-icon-60x60.png">\n<link rel="apple-touch-icon" sizes="72x72" href="/img/icons/apple-icon-72x72.png">\n<link rel="apple-touch-icon" sizes="76x76" href="/img/icons/apple-icon-76x76.png">\n<link rel="apple-touch-icon" sizes="114x114" href="/img/icons/apple-icon-114x114.png">\n<link rel="apple-touch-icon" sizes="120x120" href="/img/icons/apple-icon-120x120.png">\n<link rel="apple-touch-icon" sizes="144x144" href="/img/icons/apple-icon-144x144.png">\n<link rel="apple-touch-icon" sizes="152x152" href="/img/icons/apple-icon-152x152.png">\n<link rel="apple-touch-icon" sizes="180x180" href="/img/icons/apple-icon-180x180.png">\n<link rel="icon" type="image/png" sizes="192x192" href="/img/icons/android-icon-192x192.png">\n<link rel="icon" type="image/png" sizes="32x32" href="/img/icons/favicon-32x32.png">\n<link rel="icon" type="image/png" sizes="96x96" href="/img/icons/favicon-96x96.png">\n<link rel="icon" type="image/png" sizes="16x16" href="/img/icons/favicon-16x16.png">\n<link rel="manifest" href="/img/icons/manifest.json">\n<link rel="alternate" hreflang="de" href="https://companiesmarketcap.com/de/tesla/umsatz/" />\n<link rel="alternate" hreflang="fr" href="https://companiesmarketcap.com/fr/tesla/revenu/" />\n<link rel="alternate" hreflang="en-US" href="https://companiesmarketcap.com/tesla/revenue/" />\n<link rel="alternate" hreflang="en-IE" href="https://companiesmarketcap.com/eur/tesla/revenue/" />\n<link rel="alternate" hreflang="en-IN" href="https://companiesmarketcap.com/inr/tesla/revenue/" />\n<link rel="alternate" hreflang="en-GB" href="https://companiesmarketcap.com/gbp/tesla/revenue/" />\n<link rel="alternate" hreflang="en-CA" href="https://companiesmarketcap.com/cad/tesla/revenue/" />\n<link rel="alternate" hreflang="en-AU" href="https://companiesmarketcap.com/aud/tesla/revenue/" />\n<link rel="alternate" hreflang="en-NZ" href="https://companiesmarketcap.com/nzd/tesla/revenue/" />\n<link rel="alternate" hreflang="en-HK" href="https://companiesmarketcap.com/hkd/tesla/revenue/" />\n<link rel="alternate" hreflang="en-SG" href="https://companiesmarketcap.com/sgd/tesla/revenue/" />\n<link rel="canonical" href="https://companiesmarketcap.com/tesla/revenue/" />\n<meta property="og:url" content="https://companiesmarketcap.com/tesla/revenue/" />\n<meta name="robots" content="INDEX,FOLLOW" />\n<meta name="msapplication-TileColor" content="#ffffff">\n<meta name="msapplication-TileImage" content="/img/icons/ms-icon-144x144.png">\n<meta name="theme-color" content="#ffffff">\n<meta name="viewport" content="width=device-width, initial-scale=1.0">\n<meta http-equiv="content-language" content="en-US">\n<meta property="og:title" content="Tesla (TSLA) - Revenue"><meta property="og:type" content="website" />\n<meta property="og:description" content="Current and historical revenue charts for Tesla. As of May 2026 Tesla\'s TTM revenue is of $94.82 Billion USD">\n<meta property="og:image" content="https://companiesmarketcap.com/logo.png">\n<meta name="description" content="Current and historical revenue charts for Tesla. As of May 2026 Tesla\'s TTM revenue is of $94.82 Billion USD">\n<link rel="stylesheet" type="text/css" href="/bt-replacement.css?v=9">\n<link rel="stylesheet" type="text/css" href="/css/style.css?v=348">\n<script>\ncurrent_locale = "usd";\ncurrent_locale_path = "";\n\ncurrent_marketcap_path = "marketcap";\n</script>\n\n<script async src="https://cdn.fuseplatform.net/publift/tags/2/3432/fuse.js"></script></head>\n<body class="cmkt" id="cmkt">\n\n<div class="row site-header-row">\n    <div class="site-header">\n        <span style="display: inline-flex; margin-top: 2px;">\n                <span class="max-width-720px-hidden">\n                        Companies: <span class="font-weight-bold">10,813</span> &nbsp;&nbsp;&nbsp;\n                        total market cap: <span class="font-weight-bold"><a class="total-mcap-link" href="/total-marketcap/">$147.410 T</a></span>\n                </span>\n        </span>\n        <div class="header-actions">\n                                        <a class="header-button sign-in-button sign-in" href="#">Sign In</a>\n                                \n\n                <div class="dropdown currency-dropdown">\n                        <a href="#" class="header-button dropdown-toggle" id="languageDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">\n                        🇺🇸 <span class="responsive-shown-inline">EN</span><span class="responsive-hidden">English</span>                        </a>\n                        <div class="dropdown-menu currency-menu" aria-labelledby="languageDropdown">\n                                <a class="dropdown-item" onclick="document.cookie = \'pref_language=DE;  max-age=91536000000; path=/;\';" href="/de/tesla/umsatz/">🇩🇪 Deutsch</a><a class="dropdown-item" onclick="document.cookie = \'pref_language=FR;  max-age=91536000000; path=/;\';" href="/fr/tesla/revenu/">🇫🇷 Français</a>                        </div>\n                </div>\n\n                <div class="dropdown currency-dropdown">\n                        <a href="#" class="header-button dropdown-toggle" id="currencyDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">\n                        $ USD                        </a>\n                        <div class="dropdown-menu currency-menu" aria-labelledby="currencyDropdown">\n                                <a class="dropdown-item" onclick="document.cookie = \'pref_currency=EUR;  max-age=91536000000; path=/;\';" href="/eur/tesla/revenue/"><span class="symbol">€</span><span class="currency-code">EUR</span><span class="currency-flag">🇪🇺</span></a><a class="dropdown-item" onclick="document.cookie = \'pref_currency=INR;  max-age=91536000000; path=/;\';" href="/inr/tesla/revenue/"><span class="symbol">₹</span><span class="currency-code">INR</span><span class="currency-flag">🇮🇳</span></a><a class="dropdown-item" onclick="document.cookie = \'pref_currency=GBP;  max-age=91536000000; path=/;\';" href="/gbp/tesla/revenue/"><span class="symbol">£</span><span class="currency-code">GBP</span><span class="currency-flag">🇬🇧</span></a><a class="dropdown-item" onclick="document.cookie = \'pref_currency=CAD;  max-age=91536000000; path=/;\';" href="/cad/tesla/revenue/"><span class="symbol">$</span><span class="currency-code">CAD</span><span class="currency-flag">🇨🇦</span></a><a class="dropdown-item" onclick="document.cookie = \'pref_currency=AUD;  max-age=91536000000; path=/;\';" href="/aud/tesla/revenue/"><span class="symbol">$</span><span class="currency-code">AUD</span><span class="currency-flag">🇦🇺</span></a><a class="dropdown-item" onclick="document.cookie = \'pref_currency=NZD;  max-age=91536000000; path=/;\';" href="/nzd/tesla/revenue/"><span class="symbol">$</span><span class="currency-code">NZD</span><span class="currency-flag">🇳🇿</span></a><a class="dropdown-item" onclick="document.cookie = \'pref_currency=HKD;  max-age=91536000000; path=/;\';" href="/hkd/tesla/revenue/"><span class="symbol">$</span><span class="currency-code">HKD</span><span class="currency-flag">🇭🇰</span></a><a class="dropdown-item" onclick="document.cookie = \'pref_currency=SGD;  max-age=91536000000; path=/;\';" href="/sgd/tesla/revenue/"><span class="symbol">$</span><span class="currency-code">SGD</span><span class="currency-flag">🇸🇬</span></a>                        </div>\n                </div>\n\t\t\n                \n\n\t\t<a href="#" class="dark-hidden" id="light-off-btn" title="change to dark mode">\n\t\t\t<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 70 1000 1000" width="16" height="16">\n\t\t\t\t<path d="M525.3,989.5C241.2,989.5,10,758.3,10,474.1c0-196.8,109.6-373.6,285.9-461.4c7.9-3.9,17.5-2.4,23.7,3.8c6.2,6.2,7.9,15.8,4,23.7c-32.2,65.4-48.5,135.7-48.5,208.9c0,261.4,212.7,474.1,474.1,474.1c74,0,145-16.7,211-49.5c7.9-3.9,17.5-2.4,23.7,3.8c6.3,6.3,7.9,15.8,3.9,23.7C900.5,879,723.3,989.5,525.3,989.5z"></path>\n\t\t\t</svg>\n\t\t</a>\n\t\t<a href="#" class="dark-shown" id="light-on-btn" title="change to light mode">\n\t\t\t<svg xmlns="http://www.w3.org/2000/svg" viewBox="10 10 220 220" width="16" height="16">\n\t\t\t\t<path d="M120,189.697c-38.492,0-69.696-31.205-69.696-69.697S81.508,50.303,120,50.303c38.494,0,69.699,31.205,69.699,69.697 S158.494,189.697,120,189.697z M203.975,140L240,120l-36.025-20V140z M36.025,100L0,120l36.025,20V100z M120,240l20-36.025h-40 L120,240z M120,0l-20,36.025h40L120,0z M46.481,165.238l-11.333,39.615l39.616-11.33L46.481,165.238z M165.238,46.477l28.283,28.285 l11.332-39.613L165.238,46.477z M35.148,35.148L46.48,74.762l28.283-28.285L35.148,35.148z M165.238,193.523l39.615,11.33 l-11.332-39.615L165.238,193.523z"/>\n\t\t\t</svg>\n\t\t</a>\n        </div>\n    </div>\n</div>\n<nav class="navbar nav-bar-companiesmarketcap navbar-expand-lg navbar-light">\n  <div class="navbar-collapse-container">\n  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">\n    <span class="navbar-toggler-icon"></span>\n  </button>\n\n    <form class="search-form form-inline">\n      <input id="search-input" class="form-control search-input" type="search" placeholder="Company name, ticker..." aria-label="Company name, ticker..." autocomplete="off">\n      <button onclick="return false;" class="btn-search" type="submit" disabled=""><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 14 14" width="18" height="18"><g stroke-width="2" stroke="#6c6c6c" fill="none"><path d="M11.29 11.71l-4-4"></path><circle cx="5" cy="5" r="4"></circle></g></svg></button>\n      <div id="typeahead-search-results" class="typeahead-search-results"></div>\n    </form>\n\n  <div class="collapse navbar-collapse" id="navbarSupportedContent">\n\n    <a href="/" title="CompaniesMarketCap.com - companies ranked by market capitalization" class="responsive-hidden">\n\t<div class="companiesmarketcap-logo"></div>\n    </a>\n    <ul class="navbar-nav">\n      <li class="nav-item">\n        <a class="nav-link nav-link-companiesmarketcap" href="/">Global ranking</a>\n      </li>\n      <li class="nav-item dropdown megamenu-li">\n       <a class="nav-link nav-link-companiesmarketcap dropdown-toggle" href="#" id="dropdown-countries" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Ranking by countries</a>\n       <div class="dropdown-menu megamenu" aria-labelledby="dropdown-countries">\n        <div class="row">\n         <div class="col-sm-6 col-lg-3">\n          <h5>America</h5>\n          <a class="dropdown-item" href="/usa/largest-companies-in-the-usa-by-market-cap/">🇺🇸 United States</a>\n          <a class="dropdown-item" href="/canada/largest-companies-in-canada-by-market-cap/">🇨🇦 Canada</a>\n          <a class="dropdown-item" href="/mexico/largest-companies-in-mexico-by-market-cap/">🇲🇽 Mexico</a>\n          <a class="dropdown-item" href="/brazil/largest-companies-in-brazil-by-market-cap/">🇧🇷 Brazil</a>\n          <a class="dropdown-item" href="/chile/largest-companies-in-chile-by-market-cap/">🇨🇱 Chile</a>\n         </div>\n         <div class="col-sm-6 col-lg-3 border-left">\n          <h5>Europe</h5>\n          <a class="dropdown-item" href="/european-union/largest-companies-in-the-eu-by-market-cap/">🇪🇺 European Union</a>\n          <a class="dropdown-item" href="/germany/largest-companies-in-germany-by-market-cap/">🇩🇪 Germany</a>\n          <a class="dropdown-item" href="/united-kingdom/largest-companies-in-the-uk-by-market-cap/">🇬🇧 United Kingdom</a>\n          <a class="dropdown-item" href="/france/largest-companies-in-france-by-market-cap/">🇫🇷 France</a>\n          <a class="dropdown-item" href="/spain/largest-companies-in-spain-by-market-cap/">🇪🇸 Spain</a>\n          <a class="dropdown-item" href="/netherlands/largest-companies-in-the-netherlands-by-market-cap/">🇳🇱 Netherlands</a>\n          <a class="dropdown-item" href="/sweden/largest-companies-in-sweden-by-market-cap/">🇸🇪 Sweden</a>\n          <a class="dropdown-item" href="/italy/largest-companies-in-italy-by-market-cap/">🇮🇹 Italy</a>\n          <a class="dropdown-item" href="/switzerland/largest-companies-in-switzerland-by-market-cap/">🇨🇭 Switzerland</a>\n          <a class="dropdown-item" href="/poland/largest-companies-in-poland-by-market-cap/">🇵🇱 Poland</a>\n          <a class="dropdown-item" href="/finland/largest-companies-in-finland-by-market-cap/">🇫🇮 Finland</a>\n         </div>\n         <div class="col-sm-6 col-lg-3 border-left">\n          <h5>Asia</h5>\n          <a class="dropdown-item" href="/china/largest-companies-in-china-by-market-cap/">🇨🇳 China</a>\n          <a class="dropdown-item" href="/japan/largest-companies-in-japan-by-market-cap/">🇯🇵 Japan</a>\n          <a class="dropdown-item" href="/south-korea/largest-companies-in-south-korea-by-market-cap/">🇰🇷 South Korea</a>\n          <a class="dropdown-item" href="/hong-kong/largest-companies-in-hong-kong-by-market-cap/">🇭🇰 Hong Kong</a>\n          <a class="dropdown-item" href="/singapore/largest-companies-in-singapore-by-market-cap/">🇸🇬 Singapore</a>\n          <a class="dropdown-item" href="/indonesia/largest-companies-in-indonesia-by-market-cap/">🇮🇩 Indonesia</a>\n          <a class="dropdown-item" href="/india/largest-companies-in-india-by-market-cap/">🇮🇳 India</a>\n          <a class="dropdown-item" href="/malaysia/largest-companies-in-malaysia-by-market-cap/">🇲🇾 Malaysia</a>\n          <a class="dropdown-item" href="/taiwan/largest-companies-in-taiwan-by-market-cap/">🇹🇼 Taiwan</a>\n          <a class="dropdown-item" href="/thailand/largest-companies-in-thailand-by-market-cap/">🇹🇭 Thailand</a>\n          <a class="dropdown-item" href="/vietnam/largest-companies-in-vietnam-by-market-cap/">🇻🇳 Vietnam</a>\n\n         </div>\n         <div class="col-sm-6 col-lg-3 border-left">\n          <h5>Others</h5>\n          <a class="dropdown-item" href="/australia/largest-companies-in-australia-by-market-cap/">🇦🇺 Australia</a>\n          <a class="dropdown-item" href="/new-zealand/largest-companies-in-new-zealand-by-market-cap/">🇳🇿 New Zealand</a>\n          <a class="dropdown-item" href="/israel/largest-companies-in-israel-by-market-cap/">🇮🇱 Israel</a>\n          <a class="dropdown-item" href="/saudi-arabia/largest-companies-in-saudi-arabia-by-market-cap/">🇸🇦 Saudi Arabia</a>\n          <a class="dropdown-item" href="/turkey/largest-companies-in-turkey-by-market-cap/">🇹🇷 Turkey</a>\n          <a class="dropdown-item" href="/russia/largest-companies-in-russia-by-market-cap/">🇷🇺 Russia</a>\n          <a class="dropdown-item" href="/south-africa/largest-companies-in-south-africa-by-market-cap/">🇿🇦 South Africa</a>\n          <a class="dropdown-item" href="/all-countries/"><strong>&#x3E;&#x3E; All Countries</strong></a>\n         </div>\n        </div>\n       </div>\n      </li>\n      <li class="nav-item dropdown megamenu-li">\n       <a class="nav-link nav-link-companiesmarketcap dropdown-toggle" href="#" id="dropdown-categories" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Ranking by categories</a>\n       <div class="dropdown-menu megamenu" aria-labelledby="dropdown-categories">\n        <div class="row">\n         <div class="col-sm-6 col-lg-3">\n          <a class="dropdown-item" href="/assets-by-market-cap/">🏆 All assets by Market Cap</a>\n          <a class="dropdown-item" href="/automakers/largest-automakers-by-market-cap/">🚗 Automakers</a>\n          <a class="dropdown-item" href="/airlines/largest-airlines-by-market-cap/">✈️  Airlines</a>\n          <a class="dropdown-item" href="/airports/largest-airport-operating-companies-by-market-cap/">🛫 Airports</a>\n          <a class="dropdown-item" href="/aircraft-manufacturers/largest-aircraft-manufacturers-by-market-cap/">✈️  Aircraft manufacturers</a>\n          <a class="dropdown-item" href="/banks/largest-banks-by-market-cap/">🏦 Banks</a>\n          <a class="dropdown-item" href="/hotels/largest-hotel-companies-by-market-cap/">🏨 Hotels</a>\n          <a class="dropdown-item" href="/pharmaceuticals/largest-pharmaceutical-companies-by-market-cap/">💊 Pharmaceuticals</a>\n          <a class="dropdown-item" href="/e-commerce/largest-e-commerce-companies-by-market-cap/">🛒 E-Commerce</a>\n          <a class="dropdown-item" href="/healthcare/largest-healthcare-companies-by-market-cap/">⚕️ Healthcare</a>\n         </div>\n         <div class="col-sm-6 col-lg-3 border-left">\n          <a class="dropdown-item" href="/delivery-services/largest-delivery-companies-by-market-cap/">📦 Courier services</a>\n          <a class="dropdown-item" href="/media-press/largest-media-and-press-companies-by-market-cap/">📰 Media/Press</a>\n          <a class="dropdown-item" href="/alcoholic-beverages/largest-alcoholic-beverage-companies-by-market-cap/">🍷 Alcoholic beverages</a>\n          <a class="dropdown-item" href="/beverages/largest-beverage-companies-by-market-cap/">🥤 Beverages</a>\n          <a class="dropdown-item" href="/clothing/largest-clothing-companies-by-market-cap/">👚 Clothing</a>\n          <a class="dropdown-item" href="/mining/largest-mining-companies-by-market-cap/">⛏️ Mining</a>\n          <a class="dropdown-item" href="/railways/largest-railways-companies-by-market-cap/">🚂 Railways</a>\n          <a class="dropdown-item" href="/insurance/largest-insurance-companies-by-market-cap/">🏦 Insurance</a>\n          <a class="dropdown-item" href="/real-estate/largest-real-estate-companies-by-market-cap/">🏠 Real estate</a>\n         </div>\n         <div class="col-sm-6 col-lg-3 border-left">\n          <a class="dropdown-item" href="/ports/largest-port-operating-companies-by-market-cap/">⚓ Ports</a>\n          <a class="dropdown-item" href="/professional-services/largest-professional-service-companies-by-market-cap/">💼 Professional services</a>\n          <a class="dropdown-item" href="/food/largest-food-companies-by-market-cap/">🍴 Food</a>\n          <a class="dropdown-item" href="/restaurant-chains/largest-restaurant-chain-companies-by-market-cap/">🍔 Restaurant chains</a>\n          <a class="dropdown-item" href="/software/largest-software-companies-by-market-cap/">\u200d💻 Software</a>\n          <a class="dropdown-item" href="/semiconductors/largest-semiconductor-companies-by-market-cap/">📟 Semiconductors</a>\n          <a class="dropdown-item" href="/tobacco/largest-tobacco-companies-by-market-cap/"> 🚬 Tobacco</a>\n          <a class="dropdown-item" href="/financial-services/largest-financial-service-companies-by-market-cap/">💳 Financial services</a>\n          <a class="dropdown-item" href="/oil-gas/largest-oil-and-gas-companies-by-market-cap/">🛢 Oil&amp;Gas</a>\n          <a class="dropdown-item" href="/electricity/largest-electricity-companies-by-market-cap/">🔋 Electricity</a>\n         </div>\n         <div class="col-sm-6 col-lg-3 border-left">\n          <a class="dropdown-item" href="/chemicals/largest-chemical-companies-by-market-cap/">🧪 Chemicals</a>\n          <a class="dropdown-item" href="/investment/largest-investment-companies-by-market-cap/">💰 Investment</a>\n          <a class="dropdown-item" href="/telecommunication/largest-telecommunication-companies-by-market-cap/">📡 Telecommunication</a>\n          <a class="dropdown-item" href="/retail/largest-retail-companies-by-market-cap/">🛍️ Retail</a>\n          <a class="dropdown-item" href="/internet/largest-internet-companies-by-market-cap/">🖥️ Internet</a>\n          <a class="dropdown-item" href="/construction/largest-construction-companies-by-market-cap/">🏗 Construction</a>\n          <a 

In [23]:
#Parsing the data with beautiful soup
parse_revenue_tesla = BeautifulSoup(html_tesla, "html.parser")

In [31]:
table_revenue_tesla = parse_revenue_tesla.find("table")
rows = table_revenue_tesla.find("tbody").find_all("tr")

final_data_tesla = []

for row in rows:
    columns = row.find_all("td")
    year = columns[0].text
    revenue = columns[1].text
    
    final_data_tesla.append({'Year': year,
                       'Revenue': revenue})

revenue_tesla = pd.DataFrame(final_data_tesla) 
revenue_tesla

     Year   Revenue
0   2025   $94.82 B
1   2024   $97.69 B
2   2023   $96.77 B
3   2022   $81.46 B
4   2021   $53.82 B
5   2020   $31.53 B
6   2019   $24.57 B
7   2018   $21.46 B
8   2017   $11.75 B
9   2016    $7.00 B
10  2015    $4.04 B
11  2014    $3.19 B
12  2013    $2.01 B
13  2012    $0.41 B
14  2011    $0.20 B
15  2010    $0.11 B
16  2009    $0.11 B

#### Gamestop Revenue

In [38]:
url_gamestop = 'https://companiesmarketcap.com/gamestop/revenue/'
html_gme = requests.get(url_gamestop).text

In [39]:
#Parsing with beautiful soup
parse_revenue_gme = BeautifulSoup(html_gme, "html.parser")

In [48]:
table_revenue_gme = parse_revenue_gme.find("table")
rows_gme = table_revenue_gme.find("tbody").find_all("tr")

final_data_gme = []

for row in rows_gme:
    cols = row.find_all("td")
    year = cols[0].text
    revenue = cols[1].text

    final_data_gme.append({'Year': year,
                           'Revenue': revenue})
    
revenue_gme = pd.DataFrame(final_data_gme)
revenue_gme

           Year  Revenue
0   2025 (TTM)   $3.80 B
1         2024   $3.82 B
2         2023   $5.27 B
3         2022   $5.92 B
4         2021   $6.01 B
5         2020   $5.08 B
6         2019   $6.46 B
7         2018   $7.84 B
8         2017   $9.22 B
9         2016   $8.60 B
10        2015   $9.36 B
11        2014   $9.29 B
12        2013   $9.03 B
13        2012   $8.88 B
14        2011   $9.55 B
15        2010   $9.47 B
16        2009   $9.07 B
17        2008   $8.80 B
18        2007   $7.09 B
19        2006   $5.31 B
20        2005   $3.09 B
21        2004   $1.84 B
22        2003   $1.57 B
23        2002   $1.35 B
24        2001   $1.12 B

# Section 4: Cleaning Data

# Section 5: Visualization

# Section 6: Conclusions